name: build and run test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v1.1.11
      
      - name: Install oPam
        run: eval $(opam env); sh setup-opam

      - name: Run Test
        run: eval $(opam env); dune runtest
